# Created with WinGet Releaser using komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Kopi-vm.Kopi
PackageVersion: 0.1.2
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2025-08-21
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Kopi\bin'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/kopi-vm/kopi/releases/download/v0.1.2/kopi-0.1.2-windows-x64.msi
  InstallerSha256: D948503A4CF0C4DCECE3CD236D00E9154CD93689CFA4BECA456D00CAA55E8802
  ProductCode: '{E246D3A3-BB73-4366-99FB-E447C462D698}'
  AppsAndFeaturesEntries:
  - Publisher: Kopi Contributors
    ProductCode: '{E246D3A3-BB73-4366-99FB-E447C462D698}'
    UpgradeCode: '{6503F7D2-998F-412B-8D34-B6B2073CF939}'
- Architecture: arm64
  InstallerUrl: https://github.com/kopi-vm/kopi/releases/download/v0.1.2/kopi-0.1.2-windows-arm64.msi
  InstallerSha256: 53676DDF1A135CE0919F079FAF9C83A8241E4D929CA237B1A5149F73BC7F2E90
  ProductCode: '{9896B9FD-A000-4A76-9DB8-4FC60A746255}'
  AppsAndFeaturesEntries:
  - Publisher: Kopi Contributors
    ProductCode: '{9896B9FD-A000-4A76-9DB8-4FC60A746255}'
    UpgradeCode: '{6503F7D2-998F-412B-8D34-B6B2073CF939}'
ManifestType: installer
ManifestVersion: 1.10.0
